print('Divisão do segundo número pelo primeiro')
valor1 = int(input('Digite seu primeiro número: '))
valor2 = int(input('Digite seu segundo número: '))
resultado = int(valor2 / valor1)
print(f'O resultado da divisão é: {resultado}')